#Author:never give up    just do it
code_name = ("opple")
print(code_name.join("sss"))
print(code_name.ljust(50,"$"))
print(code_name.rjust(50,"$"))
print("\naasdada\n".strip())
m = str.maketrans('asdasfdf','12312414')
print('asddadasf'.translate(m))
print("code v".rindex("v"))
print("1=2=3=4".split("="))
print("code V".swapcase())
print("code v".zfill(30))


# print(code_name.count("o"))
# print(code_name.capitalize())
# print(code_name.center(50,"+"))
# print(code_name.encode())
print(code_name.expandtabs(tabsize=50))
#
# code_name = ("opple{0}")
# print(code_name.format("solo"))
# code_name = ("o{z}pp{a}le")
# print(code_name.format_map({'z':'x','a':'y'}))
# print(code_name.find("l"))
# print(code_name.index("le"))

# print(code_name.isdecimal())
# print(code_name.istitle())
# print(code_name.isdecimal())
# print(code_name.isalnum())
# print(code_name.isidentifier())
# print(code_name.isupper())
# print(code_name.islower())
# print(code_name.isnumeric())
# print(code_name.isspace())
